### DISCUSSION TITLE
Can someone explain why the cursor does not change in insert mode or visual mode once it is set?

### DISCUSSION THREAD

**Discussion by HeavenTao** [contour-terminal/contour#1105] [Q&A] [answered]
On my computer, Contour is the most performance-oriented terminal emulator. However, it has one drawback, and I have also noticed in the configuration file that you can currently only set the cursor style but not the insert mode or visual mode. Can you explain why?
Thanks！🙏

**Comment by uspasojevic96** [comment]
This is a nice feature request, so you want something to how NVim does things where you can differentiate between modes based on cursor style?

**Comment by christianparpart** [comment]
@HeavenTao Hey, many thanks for your interest. This is actually a great idea. Out of curiosity, are you currently on master branch (manually build / tarballs from CI) or on latest release?

If I am not misunderstanding this, that should be a great thing to implement that certainly won't take long to land on master branch :)

**Comment by christianparpart** [comment, marked as answer]
Okay, I am sorry for the confusion, @HeavenTao. I have obviously typed too fast, an hour ago. I've checked the code now, and despite having this functionality already, I've fixed a bug along the way wrt that configuration.

Keep watching PR #1106 to be merged and then maybe update to latest master branch (?).

Configuration shall work as follows:

```yaml
# ...

profiles:
    your_profile:
        cursor:
            # that's basically the cursor config for insert input mode
            shape: "bar"
            blinking: false
            blinking_interval: 500
        normal_mode:
            cursor:
                shape: block
                blinking: false
                blinking_interval: 500
        visual_mode:
            cursor:
                shape: rectangle
                blinking: false
                blinking_interval: 500
```

That's what I have locally configured, and with the above PR also works reliably. :)

For possible values for `shape`, have a look at the default configuration for `contour.yml` (also here: https://github.com/contour-terminal/contour/blob/master/src/contour/contour.yml)

I hope this helps.
