### DISCUSSION TITLE
JetBrainsMono Nerd Font does not render correctly

### DISCUSSION THREAD

**Discussion by hajirasyafi** [contour-terminal/contour#1560] [Q&A] [answered]
I used Contour with Neovim, and used JetBrainsMono Nerd Font. But it seems some icons are not rendering properly.

Contour Terminal : 
<img width="200" alt="Screenshot 2024-07-05 at 08 23 08" src="https://github.com/contour-terminal/contour/assets/46818416/5268ef03-9f95-4412-9b9e-3a36ae25f6e9">

other terminal : 
<img width="200" alt="Screenshot 2024-07-05 at 08 23 20" src="https://github.com/contour-terminal/contour/assets/46818416/84d098bb-97f0-450f-9d15-c17f87853865">

this is my configuration : 

```yml
# contour.yml
font:
   regular: "JetBrainsMono Nerd Font"
   bold: "JetBrainsMono Nerd Font"
   italic: "JetBrainsMono Nerd Font"
   bold_italic: "JetBrainsMono Nerd Font"
```
