### DISCUSSION TITLE
How to setup Contour to use WSL?

### DISCUSSION THREAD

**Discussion by KoinBanks** [contour-terminal/contour#1564] [Q&A]
Hi, I can't find the answer anywhere. I figured out I need to use the `shell: "ssh <container>"` - but what exactly should I put for  `<container>`? 

Thanks.

**Comment by Yaraslaut** [comment]
Hi @iFarmGolems, you can check out ssh section here: http://contour-terminal.org/configuration/profiles/#ssh
TLDR:
in your config file you can set 
```
profiles:
  main:
    ssh:
      host: localhost
      port: 22
      user: yaraslau
```
to connect to wsl. 
This is equivalent to the connection via standard ssh client via command `ssh.exe yaraslau@localhost`
