### DISCUSSION TITLE
Color Management

### DISCUSSION THREAD

**Discussion by regevran** [contour-terminal/contour#1759] [Q&A] [answered]
I tried to read (a few times) [colors](https://contour-terminal.org/configuration/colors/) management and failed. I think some background is missing in the documentation. 
Specifically I have two annoying issues I would like to get rid of / change:
* When I select something with the mouse, all same text is selected too everywhere, and it keep being selected even if I open an editor or whatnot. The only way I know of to get rid of this selection is to select nothing with the mouse. This is annoying.
* Highlighted search results are in the wrong color for me - I can't find how to change it.

**Comment by Yaraslaut** [comment]
Hi, 
if you do not want to see different highlight for the selected text by the double click you can use:
```
        word_highlight_other:
            foreground: CellForeground
            background: CellBackground
            foreground_alpha: 1.0
            background_alpha: 1.0

```

search result from the vim mode:
```
        # Search match highlighting. Similar to selection highlighting.
        search_highlight:
            foreground: '#00ffff'
            background: CellBackground
            foreground_alpha: 1.0
            background_alpha: 1.0

        # Search match highlighting (focused term). Similar to selection highlighting.
        search_highlight_focused:
            foreground: '#8b0000'
            background: '#ffffff'
            foreground_alpha: 1.0
            background_alpha: 1.0


```

**Reply by regevran** [reply]
```     
word_highlight_other:
        foreground: CellForeground
        background: CellBackground
        foreground_alpha: 1.0
        background_alpha: 1.0
```
This doesn't work - others are still highlighted

**Reply by regevran** [reply]
The search result suggestion didn't help too.
But maybe I need to read the manual more - as I tested _inside_ vim.

**Reply by Yaraslaut** [reply]
ahhh,  this is not in the main screen but inside application, will check it

**Reply by regevran** [reply]
`word_highlight_other` - this doesn't have any effect anywhere - both inside an application or the terminal itself.

**Reply by Yaraslaut** [reply]
most likely something is wrong with your config file, you can see info about the config loading from `contour debug config`

**Reply by regevran** [reply]
I see `Loading entry: highlight_word_and_matches_on_double_click, value true` twice - I guess for the two profiles I have.
No errors in the log.
No references to `highlight` in any form.

**Reply by Yaraslaut** [reply]
in your profile you set the name of the color palette to use, for example in default config:
```
        colors: default
```

this will create the following part in the debug output 
```
[2025-05-29 21:44:18.686779] [config] Loading entry: colors
[2025-05-29 21:44:18.686784] [config] color palette loading default
[2025-05-29 21:44:18.686792] [config] *** loading default colors
.....
[2025-05-29 21:44:18.687015] [config] *** color palette is loaded

```
and during palette loading you should see info about colors that are used for `search_highlight_focused` and so on

**Reply by regevran** [reply]
I am using `one-light`:
```
[2025-05-31 09:41:43.083371] [config] color palette loading one-light
[2025-05-31 09:41:43.083375] [config] Loaded predefined color palette one-light
```

And these are the lines I have `highlight` in:
```
$ cat contour.start.log | grep highlight
[2025-05-31 09:41:43.083296] [config] Loading entry: highlight_word_and_matches_on_double_click, value true
[2025-05-31 09:41:43.083348] [config] Loading entry: vi_mode_highlight_timeout, value 100
[2025-05-31 09:41:43.083426] [config] Loading entry: highlight_word_and_matches_on_double_click, value true
[2025-05-31 09:41:43.083430] [config] Loading entry: vi_mode_highlight_timeout, value 100
```


Do I need to somehow tweak `one-light` to my needs?

**Reply by regevran** [reply]
I added under `color_schemes`:
```
     one-light:
         word_highlight_other:
             foreground: CellForeground
             background: CellBackground
             foreground_alpha: 1.0
             background_alpha: 1.0
```

Didn't help - I still see selection of others when mouse selecting text.
