### DISCUSSION TITLE
"leftovers" at the beginning of the line

### DISCUSSION THREAD

**Discussion by regevran** [contour-terminal/contour#1760] [Q&A]
Not only in Contour, it happened to me with other terminals as well - sometimes the start of the line is occupied with leftovers from previous line. I think that this is happening mostly when I press the up-arrow (searching for a previous line) and then the down-arrow - expecting to go back to empty. Also I think it is mostly when I remotely connected (ssh):
e.g.
`ran@ran-server[2025-05-26|09:41:25](kms_host_read_token_param)~/dev/scylladb$ ll /home/`
`PS1` is resolved to: `ran@ran-server[2025-05-26|09:41:25](kms_host_read_token_param)~/dev/scylladb$ `
and `ll /home/` is there, cannot be deleted, nor it is part of current line. It is simply there.
the cursor is just after the last `/`:

**Comment by Yaraslaut** [comment]
this sounds like a bad terminfo file on the remote machine 
you also can try to use direct ssh connection instead of starting the shell and then running ssh in your config you can create new profile like following:
```
    remote:
        ssh:
            host: 157.230.5.122
            port: 22
            user: root
            private_key: "~/.ssh/id_rsa"
        terminal_size:
            columns: 120
            lines: 24

```
and then `contour profile remote` will directly connect to the server
