### DISCUSSION TITLE
Are Sixel graphics supported on Windows?

### DISCUSSION THREAD

**Discussion by waf** [contour-terminal/contour#416] [Q&A] [answered]
Hi, I'm using Windows 10 and Contour 0.2.0.173. Are sixel graphics supported on this platform?

To test, I'm using ImageMagick with a small png image:

```bash
> .\magick.exe myFile.png sixel:-
```

This produces a stream of output like so (this is just an excerpt):

![image](https://user-images.githubusercontent.com/97195/133893501-0682f812-780c-4e28-bcbd-45b15b897402.png)

Here's the relevant portion of my contour.yml (it's not modified from the default):

```yml
images:
    # Enable or disable sixel scrolling (SM/RM ?80 default)
    sixel_scrolling: true
    # Configures the maximum number of color registers available when rendering Sixel graphics.
    sixel_register_count: 4096
    # If enabled, the ANSI text cursor is placed at the position of the sixel graphics cursor after
    # image rendering, otherwise (if disabled) the cursor is placed underneath the image.
    sixel_cursor_conformance: true
    # maximum width in pixels of an image to be accepted
    max_width: 1280
    # maximum height in pixels of an image to be accepted
    max_height: 720
```

Contour is really impressive, by the way, thanks for building and working on it.
