### ISSUE TITLE
Support OS accent colors in color schemes

### ISSUE THREAD

**Issue by christianparpart** [contour-terminal/contour#1243]
MacOS, Windows, as well as KDE (most likely other UNIX DEs) do support accent colors.

It would be nice to make use of that when declaring a colorscheme.
This could be mostly usefull for selection foreground/background colors, but maybe also somewhere else.

Accent colors should be mixable with other colors by `X%` in order to enable variation

### Example ideas

```yaml
default:
    # ...
    background: [accent_mix: '#bfceff', accent_factor: 0.75]
selection:
    foreground: [invert: accent]
    background: accent
```
