### ISSUE TITLE
Customizable padding around the screen

### ISSUE THREAD

**Issue by christianparpart** [contour-terminal/contour#126]
Maybe like so:

```yaml
padding:
    top: 0px
    left: 0px
    bottom: auto
    right: auto
```

Valid values would be number of pixels, or number of pixels with `px` appended, or string "auto" for auto-computation.
