### ISSUE TITLE
Allow auto-restart of sessions with bad exit code

### ISSUE THREAD

**Issue by christianparpart** [contour-terminal/contour#1326]
Allow auto-restarting sessions (local process session as well as builtin SSH sessions) when the session did exit with bad exit code or did terminate by signal (e.g. SIGSEGV, SIGHUP, etc...)

By default it maybe should not do it. Should be configurable per profile.

```yaml
profiles:
    name:
        auto_restart_on_bad_exit: true # default false
```

I'm not good at naming, but this would at least be an intuitive option.
