### ISSUE TITLE
Assign unicode ranges to fonts

### ISSUE THREAD

**Issue by classabbyamp** [contour-terminal/contour#1374]
## Abstract

nerd-fonts are a common way to add special symbols in terminal UIs (shell prompts, editors, etc). There are two ways this is implemented, a patched font or a symbols-only font. I prefer to use the symbols-only font because it allows for more flexibility and I don't need to install 2GB worth of duplicate fonts, but it does mean some form of fallback mechanism is necessary. It seems that currently this does partially work:

![image](https://github.com/contour-terminal/contour/assets/5366828/e189ed3d-4422-480c-baee-0036832af1ad)

(kitty left, contour right; notice the incorrect symbol for the `>`)

## Motivation

To ensure that certain ranges of codepoints have the correct font, I propose a configuration option that allows for assigning ranges to certain fonts. I suspect this assignment might already be possible under-the-hood, given the `font.emoji` config option.

## Specification

My thought is something like:
```yaml
font:
  symbols:
    - range: U+E5FA-U+E62B
      family: "Symbols Nerd Font"
    - range: U+E700-U+E7C5,U+F000-U+F2E0
      family: "Symbols Nerd Font"
```

## Other Implementations

https://sw.kovidgoyal.net/kitty/conf/#opt-kitty.symbol_map
