### ISSUE TITLE
Unexpected behavior when using 'builtin_box_drawing: false'

### ISSUE THREAD

**Issue by xMonody** [contour-terminal/contour#1489]
### Contour Terminal version

0.4.3

### Installer source

GitHub: release page

### Operating System

win11 23h2

### Architecture

x86

### Other Software

vim9.1 and nvim0.95

### Steps to reproduce

The minimum configuration
``` yml
platform_plugin: auto
# Word delimiters when selecting word-wise.
profiles:
    main:
        font:
            # Initial font size in pixels.
            size: 16
            locator: native
            text_shaping:
                engine: native
            builtin_box_drawing: false
            render_mode: lcd
            strict_spacing: true
            regular:
                family: "SauceCodePro Nerd Font Mono"
                weight: regular
                slant: normal
                features: []
            bold: "SauceCodePro Nerd Font Mono"
            italic: "SauceCodePro Nerd Font Mono"
            bold_italic: "SauceCodePro Nerd Font Mono"
            emoji: "emoji"
        draw_bold_text_with_bright_colors: false
```
![b99146e364c8458cf6c5fa7d1714bfed](https://github.com/contour-terminal/contour/assets/76483540/c1b73207-5f5b-4e12-8c65-13ac012e2a97)

### Actual Behavior

![b99146e364c8458cf6c5fa7d1714bfed](https://github.com/contour-terminal/contour/assets/76483540/8539eabd-4417-415c-98c2-791023a773f4)
