### ISSUE TITLE
Add customizable per-input-mode default text/background coloring for indicator statusline

### ISSUE THREAD

**Issue by christianparpart** [contour-terminal/contour#1528]
We can currently only configure the default text/background color for the indicator statusline (active window and inactive window).

The goal is to make the color adapting based on input mode.

Possible configuration could look like:

```yaml
profiles:
    your_profile_name:
        indicator_statusline:
            # default foreground/background for any non-override specified status line.
            foreground: '#808080'
            background: '#000000'
            # specific colors for the different modes
            overrides:
                # override default colors for e.g. insert_mode
                # possible also: normal_mode, visual_mode(any visual),
                #         visual_block_mode, visual_line_mode, search_mode(?)
                insert_mode:
                    foreground: '#123456'
                    background: '#abcdef'

```

## Checklist

- [ ] override for insert mode
- [ ] override for normal mode
- [ ] override for visual mode (any visual mode)
- [ ] override for visual line mode
- [ ] override for visual block mode
- [ ] documentation added
