### ISSUE TITLE
Move all config options into profiles

### ISSUE THREAD

**Issue by pxeger** [contour-terminal/contour#153]
Some options, like `scrollbar`, `input_mapping` etc. (those are the ones that matter to me), are not part of the `profiles` section in the config file. You can change these by launching contour with a different `-c` option, but it strikes me that there is no point in having profiles if you can only change *some* options using them.

<sub>PS: This issue template is silly. I'm not redesigning C or announcing a vaccine for malaria, I'm asking for a small change in a terminal emulator. I don't need an "abstract", "rationale", or "specification". At least rename them to "what is the problem", "why is this a problem", and "how do we fix it", or ideally, get rid of it.</sub>

**Comment by christianparpart** [comment]
Hey @pxeger 

Many thanks for your feedback with regards to the templates. I will attempt to improve them then. ;-)

With regards to configuration, i partly agree, but where to draw the line?

scrollbar config is easily justifiable, but with Input mapping i have some reservations in moving that into profiles for (i think) one reason: you would potentially duplicate a lot in your config if you want varying input makings in your profiles.

I am not against it (just to be clear). 

What is your motivation for that? Can you share me your ideas here, if you don't mind?

Have some nice Christmas days. ;-)

**Comment by pxeger** [comment]
> potentially duplicate a lot of your config

May I introduce you to YAML [Anchors](https://yaml.org/spec/1.2/spec.html#id2785586) and [Aliases](https://yaml.org/spec/1.2/spec.html#id2786196), designed expressly for this purpose! For example:

```yaml
profiles:
  profile_1:
    # firstly define the anchor
    input_mapping: &my_default_keymap
      - { mods: [Control, Shift], key: Q, action: Quit }
      # ...
  profile_2:
    # direct copy of the anchored section
    input_mapping: *my_default_keymap
  profile_3:
    input_mapping:
      # extend the referenced list
      - *my_default_keymap
      - { mods: [], key: F11, action: ToggleFullscreen }
      # ...
```

So I don't think this is really a problem, provided we can teach this effectively. (maybe put it in the README example config file?)

Enjoy your Christmas too!
