### ISSUE TITLE
Terminal size is not respected with profile with ssh.

### ISSUE THREAD

**Issue by kierun** [contour-terminal/contour#1708]
### Contour Terminal version

Contour Terminal Emulator 0.6.1

### Installer source

something else (please specify below)

### Operating System

Fedora 40

### Architecture

x86-64

### Other Software

OpenSSH_9.6p1, OpenSSL 3.2.2 4 Jun 2024 — I am pretty sure this is irrelevant, but ¯\\\_(ツ)\_/¯

### Steps to reproduce

1. Create this configuration:
```yml
    foo:
        ssh:
            host: foo # ← should be a real host…
            port: 22
            user: yann
        terminal_size:
            columns: 120
            lines: 24
```
2. Run `contour profile foo`
3. Notice the terminal has 80 character width, not 120.
4. Remove the ssh segment.
5. Run `contour profile foo`
6. Notice the terminal has 120 character width.

### Expected Behavior

The terminal should have a width of 120. 

### Actual Behavior

The terminal has a width of 80, the default.
