### ISSUE TITLE
Coloring of statusline does not change in insert mode

### ISSUE THREAD

**Issue by adre5577** [contour-terminal/contour#1737]
### Contour Terminal version

Contour Terminal Emulator 0.6.1

### Installer source

Something else (please specify below)

### Operating System

Manjaro with Linux 6.13.5-2

### Architecture

x86-64 / amd64

### Steps to reproduce

Change the theme. Statusline will remain the same colors while in insert mode.

### Expected Behavior

The statusline in insert mode should be the same color as in normal mode.

![Image](https://github.com/user-attachments/assets/89ec4ba4-2e75-4dda-b344-573d145c9eeb)

### Actual Behavior

The statusline remains the default color while the window is focused.

![Image](https://github.com/user-attachments/assets/9a3b3c38-a5ba-4206-a0f3-caa12159a32a)

**Comment by Yaraslaut** [comment]
Hi, thanks for the bug report, this will be fixed in the PR:  https://github.com/contour-terminal/contour/pull/1743
please also note that the color that is used for the status line in insert mode is `default`, 
```
        indicator_statusline:
            default:  <----------- THIS ONE 
            inactive:
            normal_mode:
            visual_mode:
```
