### ISSUE TITLE
(Windows) Font family doesn't change

### ISSUE THREAD

**Issue by MordechaiHadad** [contour-terminal/contour#452]
So i'm trying to change the font family for contour to JetBrains mono nerd font(the name in windows font searcher is JetBrainsMono Nerd Font) tried even to other font families such as Consolas etc but the font won't change even on contour restart

## Environment

- Contour Version or Git commit hash: 0.2.0.173
- Operating System (name / distribution / version): Windows 10 Pro 21H1
- Contour configuration: 
```yml
            regular:
                # Font family defines the font family name, such as:
                # Fira Code", "Courier New", or "monospace" (default).
                family: "JetBrainsMono Nerd Font"

                # Font weight can be one of:
                #   thin, extra_light, light, demilight, book, normal,
                #   medium, demibold, bold, extra_bold, black, extra_black.
                weight: regular

                # Font slant can be one of: normal, italic, oblique.
               slant: normal
   ```

## Steps to Reproduce
Download jetbrains mono from the nerd font website and try to change it on windows.

**Comment by christianparpart** [comment]
Just checked. Ok the default configuration is something missing.

Can you set the font locator to `DirectWrite`? Most likely you are using `fontconfig`.

I should make the platform native one the default.

**Comment by MordechaiHadad** [comment]
> 
> 
> Just checked. Ok the default configuration is something missing.
> 
> Can you set the font locator to `DirectWrite`? Most likely you are using `fontconfig`.
> 
> I should make the platform native one the default.

Works thank you very much but one glitch i guess i face is nerd fonts look a little bit weird:
Windows Terminal: ![](https://p0rn.pro/AFriendlyAndHelplessWing)
Contour: ![](https://p0rn.pro/TheSharpAndFortunateBrush)

Windows Terminal font settings:
Font Family: JetBrains Mono Nerd Font
Font Weight: Normal

Contour font settings:
Font Family: JetBrainsMono Nerd Font
Font Weight: normal
Font Slant: normal

**Comment by MordechaiHadad** [comment]
> 
> 
> try setting the font family to: `JetBrainsMono Nerd Font Mono` (note the additional Mono at the end) and change the font weight to regular if that doens't fix it

Makes it even worst: 
Font Weight: regular
Font Family: JetBrainsMono Nerd Font Mono
![](https://p0rn.pro/AnEvilAndAdhesiveStructure)

**Comment by uspasojevic96** [comment]
well @christianparpart font family look up isn't working properly most likely

**Comment by christianparpart** [comment]
i am using JetBrains Mono NF Mono in fact, too. Will be using Windows ASAP to compare and check :)

**Comment by uspasojevic96** [comment]
> > i am using JetBrains Mono NF Mono in fact, too. Will be using Windows ASAP to compare and check :)
> 
> A man of culture

The only thing that JetBrains made that doesn't suck is the font

**Comment by MordechaiHadad** [comment]
> 
> 
> > > i am using JetBrains Mono NF Mono in fact, too. Will be using Windows ASAP to compare and check :)
> > 
> > 
> > A man of culture
> 
> The only thing that JetBrains made that doesn't suck is the font

Debatable

**Comment by trackd** [comment]
any news on this issue?

I got it somewhat working using the following config:

```yaml
        font:
            size: 13
            locator: DirectWrite
            text_shaping:
                engine: DirectWrite
            builtin_box_drawing: true
            render_mode: gray
            strict_spacing: true
            regular:
                family: "JetBrainsMono Nerd Font Mono"
                weight: Regular
                slant: normal
            emoji: "JetBrainsMono Nerd Font Mono"
```

wt:
![image](https://github.com/contour-terminal/contour/assets/17672644/3b163054-0d17-4800-bcb5-64fad302382a)

contour:
![image](https://github.com/contour-terminal/contour/assets/17672644/35a6731a-2526-4b20-b26a-5e06438cc198)

the font glyphs work fine in all other applications, but VSCode does have the same spacing in the prompt, so not sure whats up with that.

glyphs used
```ps1
$Emoji            = @{
    nf_fae_comet                   = [char]0xE26D # 
    nf_md_arrange_bring_forward    = "`u{f003d}" # 󰀽
    nf_fa_folder_open_o            = [char]0xF115 # 
    nf_md_subdirectory_arrow_right = "`u{f060d}" # 󰘍
    nf_warn_icon                   = [char]0x26A0 # ⚠
    nf_oct_hourglass               = [char]0xf4e3 # 
    nf_folder_icon                 = [char]0xe5ff # 
    nf_success_icon                = [char]0xf42e # 
    nf_pom_internal_interruption   = "`u{e009}" # 
    nf_md_home                     = "`u{f02dc}" # 󰋜
    nf_pl_left_hard_divider        = [char]0xE0B0  # 
    nf_pl_right_hard_divider       = [char]0xE0B2 # 
    nf_pl_left_soft_divider        = [char]0xE0B1 # 
    nf_pl_right_soft_divider       = [char]0xE0B3 # 
    nf_ple_right_half_circle_thick = [char]0xE0B4 # 
    nf_ple_left_half_circle_thick  = [char]0xE0B6 # 
    nf_md_powershell               = "`u{f0a0a}" # 󰨊
    nf_seti_powershell             = "`u{e683}" # 
    nf_cod_terminal_powershell     = "`u{ebc7}" # 
    nf_seti_play_arrow             = "`u{e602}" # 
    nf_fa_exclamation              = [char]0xf12a # 
    nf_md_exclamation              = "`u{f0205}" # 󰈅
    nf_cod_error                   = "`u{ea87}" # 
    nf_seti_error                  = "`u{e654}" # 
    nf_md_plex                     = "`u{f06ba}" # 󰚺
    nf_fae_real_heart              = "`u{e23a}" # 
    nf_stopwatch                   = "`u{23F1}" # 󰓣
    nf_dev_code                    = "`u{e796}" # 
    minispace                      = [char]0x2009 # mini space
}
```
the minispace seem to break alot of stuff so had to disable that.
