### ISSUE TITLE
Ability to explicitly enable(/disable) font features

### ISSUE THREAD

**Issue by christianparpart** [contour-terminal/contour#520]
See:

- https://www.typography.com/faq/157
- https://github.com/tonsky/FiraCode/wiki/How-to-enable-stylistic-sets
- https://github.com/tonsky/FiraCode/issues/1203

This can be enabled in the font section by adding a feature key with an array of string values (4-letter feature names).

Example:
```yaml
font:
    family: "Fira Code"
    features: [ss01, ss02]
```
