### ISSUE TITLE
customizable statusbar

### ISSUE THREAD

**Issue by christianparpart** [contour-terminal/contour#687]
## Configuration

```yml
profiles:
    PROFILE_NAME:
        status_line:
            display: indicator # one of: none, indicator,

            # Indicator status line specific configuration.
            indicator:
                # Update interval only applies to internal process execution, e.g. for `${Shell:...}`
                update_interval: 15 # seconds
                left: "#{InputMode} #{Date:%Y-%m-%s %H:%M:%S}"
                middle: "${Title}"                 # default: empty
                right: "#{shell:uptime}"           # default: shows the current time
```

### Format specifiers

Format              | Description
--------------------|------------
`{InputMode}`       | current input mode, e.g. `NORMAL` or `INSERT`, ...
`{Shell:COMMMAND}`  | shows the output of the given command being executed using the login shell
`{Date:Format}`     | date (and/or time) in the given format, e.g. `{Date:%H:%M:%S}`
`{fg:NAME}`         | defines the foreground color for the next text
`{fg:#RRGGBB}`      | defines the foreground color in hex notation for the next text
`{bg:NAME}`         | defines the background color for the next text
`{bg:#RRGGBB}`      | defines the background color in hex notation for the next text
`{Reset}`           | resets color/styles to their defaults
`{Bold}`            | enables bold font
`{Italic}`          | enables italic font
`{Underline:STYLE}` | enables the given underline style, e.g. `normal`, `curly`, ...
`{Title}`           | current window title
`{DECModes:Pm}`     | Shows current state for VT modes of interest, a comma separated list of mode numbers
`{ANSIModes:Pm}`    | like DECModes, but for ANSI mode numbers
`{Cell:UTF8}`       | Shows the hovered cell content as an escaped UTF-8 sequence
`{Cell:UTF32}`      | Shows the hovered cell content in UTF-32 codepoint sequence
`{Cell:SGR}`        | Shows the hovered cell's SGR attribute numbers 
`{Session:IdleTime}` | Timespan since last input activity
`{Session:Uptime}`   | Uptime since session start

For `{fg:NAME}` and `{bg:NAME}` the name are color names like `red`, `green` etc or their numbers as found in the color palette (a value between `0` and `264` (inclusive) for indexed color palette access).
